[build]
publish = "public"
command = "git config core.quotePath false; hugo --gc --minify -d public;"

[context.production.environment]
HUGO_VERSION = "0.112.0"

[context.branch-deploy]
command = "hugo --minify --gc -d public -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.112.0"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.112.0"

[[headers]]
for = "/*.webp"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.jpg"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.png"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/webfonts/*"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
# Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' *.netlify.com unpkg.com ; img-src 'self' blob: data: https:; frame-ancestors 'none'; "
