# TODO
local_backend: true

backend:
  name: git-gateway
  repo: phdd/coachbar-dresden.de
  branch: main # Branch to update (optional; defaults to master)

locale: 'de'
media_folder: "static/media" # Media files will be stored in the repo under images/uploads
public_folder: "/media" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: webseite
    label: Webseite
    files:

      - label: Startseite
        name: startseite
        file: "data/home.yml"
        editor:
          preview: false
        fields:
          - label: erster Abschnitt
            name: first
            widget: object
            summary: "{{fields.title}}"
            fields:
              - { label: Überschrift, name: title, widget: string }
              - { label: Text, name: text, widget: text }
              - { label: Bild, name: image, widget: image, default: "/media/portrait.png", allow_multiple: false, hint: "500 x 650 ist optimal" }
              - label: Leistungen
                name: features
                widget: list
                fields:
                  - { label: Leistung, name: title, widget: string }
                  - { label: Icon, name: icon, widget: string, hint: "Die Liste von verfügbaren Icons ist unter https://fontawesome.com/search?o=r&m=free&s=solid zu finden" }
                  - { label: Link, name: link, widget: hidden }
                  - { label: Kurzbeschreibung, name: descr, widget: text }
          - label: zweiter Abschnitt
            name: second
            widget: object
            summary: "{{fields.title}}"
            fields:
              - { label: Überschrift, name: title, widget: string }
              - { label: Text, name: text, widget: text }
              - { label: Bild, name: image, widget: image, default: "/media/haltlos.png", allow_multiple: false, hint: "400 x 550 ist optimal" }

      - name: infos
        label: Infos & Kontakt
        file: "data/infos.yml"
        editor:
          preview: false
        fields: 
          - { label: Unternehmen, name: Unternehmen, widget: string }
          - { label: Ansprechpartner, name: Ansprechpartner, widget: string }
          - { label: Adresse, name: Adresse, widget: markdown }
          - { label: Telefon, name: Telefon, widget: string }
          - { label: E-Mail, name: Mail, widget: string }

  - name: unterseiten
    label: Unterseiten
    folder: content
    create: true
    slug: "{{ slug }}"
    editor:
      preview: false
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Beschreibung', name: 'description', widget: 'text' }
      - { label: Navigation, name: navigation, widget: select, options: ['Hauptmenü', 'Fußzeile', 'versteckt'], default: 'Hauptmenü' }
      - { label: Rank, name: weight, widget: number }
      - { label: 'Inhalt', name: 'body', widget: 'markdown' }
